apiVersion: apps/v1
kind: Deployment
metadata:
  name: meme-generator-depl
spec:
  replicas: 2
  selector:
   matchLabels:
    app: meme-app
  template:
    metadata:
      labels:
        app: meme-app
    spec:
      containers:
      - name: meme-generator
        image: disciklean/meme-generator
---
apiVersion: v1
kind: Service
metadata:
  name: meme-generator-srv
spec:
  type: NodePort
  selector:
    app: meme-app
  ports:
  - name: meme-app
    port: 3000
    targetPort: 3000
